---
title: "Smart cities in India: sketching public opinion trends on smart urban planning policies' narratives"
subtitle: "Capstone Project for Data Access and Regulation - Data Analytics for Politics Society and Complex Organizations, University of Milan" 
author: "Carola Corti - 961514"
date: "February 2021"
output: pdf_document
---

# Abstract

This project aims at collecting information about the discourse above smart cities. I will focus on India's specific case, inspecting whether the debate related to smart cities' policies' implementation in such country develops positively or negatively, what topics are the mostly discussed and which are the most problematic issues related to it.

The research will be composed of two main parts. In the first, I will provide sentiment and topic analyses processing a corpus of articles about India's smart cities development. In the second part, by interacting with the Twitter and Google Maps APIs, I will download via geographical selection the latest 2000 tweets written in India, containing the words "smart cities" and "Covid-19" . The analyses will be run, on the one hand, in order to identify the main debated topics within the smart cities broader narratives; on the other hand, to capture the overall sentiment among the texts to draw a better picture of how smart cities are perceived and what can be addressed as a criticisms or advantage in the implementation of such urban planning decisions in the perspective of both the governmental and its citizens point of view, especially in light of the Covid-19 health emergency and the known and highly debated overcrowding, poverty and diseased conditions that are common to many Indian metropolitan areas.

# Introduction

### Smart cities: definition and criticism

According to the definition provided by the European Commission, "smart cities" are places where traditional networks and services are made more efficient with the use of digital and telecommunication technologies for the benefit of its inhabitants and business. Smart metropolitan areas would do so by going beyond the use of information and communication technologies (ICT) in order to provide better resources while using less emissions. The implementation of policies aimed at providing efficient urban transport networks, upgraded water supplies, waste disposal facilities, electricity and heating technologies to let all goods reach each building and each societal stratus in the urban area, are at the heart of smart cities' goals. In other words, the underlining aim of adopting such policies is ought to implement interactive and responsive city administration strategies, guaranteeing safer public spaces and taking into consideration the needs of the whole population.

Rob Kitchin, one of the leading scholars interested in the debate about smart cities, professor and researcher of human geography at the National Institute of Regional and Spatial Analysis at Maynooth University of Ireland, states that definition of Smart City has to take into account two important aspects. On the one side, he defines as "smart" a urban context in which *everyware* technologies (Greenfield, 2006) are massively implemented. By using this term, he refers to the massively used ubiquitous computing practices, defined by human-machine interactions extended on several levels, capable of connecting physical and digital space through the continuous collection and management of the data citizens generate interacting with the surrounding material space. On the other hand, he sheds light on the importance of understanding the relationship that occurs between citizens and the technologies they interact with. The implementation of Information Communication Technologies does not in fact constitute, in itself, a necessary and sufficient condition for a city to be defined as really intelligent; it rather is the way in which datafied interactions are used and perceived by who are supposed to be its end-users, to define whether a city is "smart" or not. While it is easy to build city planning projects enthusiastically focusing on the implementation of highly advanced technologies in many fields, it is less immediate to inspect urban fabrics taking into account both the physical urban environment ( i.e. its elements, materials, form, scales, density and networks), and the psychological, socio-cultural, ecological, managerial and economic structures of metropolitan areas. The smart cities approaches have always tended, in fact, to focus on technological solutions to urban problems from the perspective of states and companies rather than critically taking into account people and communities. t is taking into account these considerations, that the debate around Smart City initiatives is more and more heated in developing countries where the ideal prerequisites to advance such policies are more likely to lack.

### Smart cities in India

This research focuses on the most prominent example In the Global South: India. This country is in fact, on the one side, a key actor in implementing national-level smart city programs, while, on the other, it constantly faces the challenges caused by an increasingly growing digital divide among its population. According to a recent World Bank report, India is the country with the largest number of non-connected citizens: data show that with a total of 1.25 billion inhabitants, more than 2billion are "offline" citizens.

However, it is precisely in India that incredibly avant-garde realities can be observed from a technological point of view (just think of the Bengaluru district, considered the Indian Silicon Valley, bulwark of technological and innovative New India). The clearest example in the urban planning context is provided by the Smart Cities Mission (SCM), a project that was launched in 2015 as a urban renewal and retrofitting program by Narendra Modi, Prime Minister of the Government of India, with the aim to develop smart cities across the country, making them citizen friendly and sustainable. The plan initially included 100 cities, planning projects to be realized between 2019 and 2023. In spite of the innovation wave the Mission wanted to follow, although extremely advanced in the technological perspective, little consideration was given to its implementation's sociological consequences.

The model of citizenship that is usually offered in smart cities contexts expects, in fact, on the one hand citizens to become "*netizens*", and, on the other, to re-configure citizenship models by instrumentalizing technology and data, reinforcing, as an unintended consequence, the patterns of exclusion for marginalized groups within the urban society, even though citizen consultation and participation are often described as the heart of smart city proposals. It is indeed not immediate for all citizens to participate actively in smart cities projects, and, whether some can, other are excluded, leading to the exacerbation of existing urban historical, material and social inequalities (Katherine S.Willis, 2019).

For instance, the city of Chennai, Located on the Coromandel Coast of the Bay of Bengal, provides clear example of the possible implications such urban planning policies have generated for marginalized communities. In Chennai, the area-based development proposals were mainly focused around the assurance of electrical and water supply, the recycling of waste water, waste management, rain water harvesting and management at households and community levels and Wi-Fi connectivity in order to integrate public transports' utilities. In spite of what could appear at first glance, as Katherine S. Willis points out in her research on India's smart cities projects, the proposed solutions, although trying to lead to concrete changes in the life-quality within the city area, failed to recognize or give value to the existing urban informality, being rather driven and rationalized by technological deterministic market plans. Urban Informality appeared to be therefore treated as a set of conditions and resources equivalent to "leaks" in a system that needed to be optimized and rationalized. As a consequence, many plans outlined in 2016 for the Smart City Chennai have failed to be realized, being even criticized through demonstrations of public protests in which banners containing writings such as "*We want bread and butter, not Smart City*" were exposed.

### Covid-19 and urban settlements in India

With an estimated 90 percent of all reported COVID-19 cases, urban areas have became the epicenter of the pandemic. The virus have, in fact, highlighted the critical role local governments play as front-line responders within the health crisis context. In this perspective, in this last year, tackling inequalities and development deficits has became of primary importance when it comes to designing policies briefs aimed at preventing the spread of the virus. Coronavirus has been widening existing social, spacial and economic inequalities in cities both in the Global North and in the Global South. It has in fact became clear that vulnerability to COVID- 19 depends on several conditions: where in a city a person lives and works, gender, age, income level, type of home, access to public services - such as health facilities- transportation and clean water. Data collected by the United Nations and reported in the UN 2020 Policy Brief "*Covid-19 in an Urban World*" , suggest that the poorer neighborhoods and those with the largest households size were more likely to experience a high number of cases per capita. India, with its 35.2% of the country's whole population living in slums and informal settlements, constitutes a paradigmatic example, since many homes in such areas lack access to water and sanitation facilities, making, for example, safe and regular handwashing extremely difficult. It is in this context that the smart policies applied to urban centers were mainly aimed at stemming the contagion.

How have smart cities addressed the pandemic in India? What issues and what type of narratives have been used to overcome the difficulties the virus have risen? What was the citizens' response in terms of trust/distrust in smart policies and local governance?

In the next sessions I will analyze the sentiment and the mainly addressed topics and issues related on the one side to smart urban planning policies implementations in such country, while on the other side taking into account the role Covid-19 has played in such context.

# Building a corpus of articles via web scraping: Smart Cities Council India  

## Step 1: /robots.txt file inspection

To check whether the website's rules permitted to perform web scraping on that page, i checked the robots.txt file. As a result, the following lines of code are shown:

The website shows it instructions to web robots by using the Robots Exclusion Protocol. The first line tells us this section applies to all robots; the second tells no robot can crawl the "/wp-admin/" page, namely the control dashboard of the entire WordPress website, while the last one tells the website is allowed to be crawled.

## Step 2: Selecting CSS paths from the DOM structure via Selector Gadget

After having inspected the /robots.txt file, I've selected the parts of the web page I need to take into account to build the corpus on which I'll perform text analytics. I'll use selector Gadget, which will help me generating by a simple point-click operation the CSS tag I need to extract the elements I'm looking for.

## Step 3: extracting the articles

# TWITTER: how do people talk about smart cities?

# Conclusions

# References
