---
title: "Smart cities in India: sketching public opinion trends on smart urban planning policies"
author: "Carola Corti- 961514"
date: "February 2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Abstract

This project aims at collecting information about the discourse above smart cities. I will focus on India's specific case, inspecting whether the debate related to smart cities' policies' implementation in such country develops positively or negatively, what topics are the mostly discussed and which are the most problematic issues related to it. The research will be composed of two main parts. In the first part, I will provide sentiment and topic analyses processing a corpus of articles about India's smart cities development. In the second part, by interacting with the Twitter and Google Maps APIs, I will download via geographical selection the latest 2000 tweets written in India, containing the words "smart cities" and "Covid-19" . The analyses will be run, on the one hand, in order to identify the main debated topics within the smart cities broader narratives; on the other hand, to capture the overall sentiment among the texts to draw a better picture of how smart cities are perceived and what can be addressed as a criticisms or advantage in the implementation of such urban planning decisions, especially in light of the Covid-19 health emergency and the known overcrowding, poverty and diseased conditions common to many Indian cities.

# Introduction

# URBANET: scraping articles about India smart urban planning

In this first session I will provide a textual analysis of the articles about smart cities in India collected in the [URBANET](https://www.urbanet.info/) web page. This digital blog fosters international dialogue on development activities worldwide and shares expertise in the areas of municipal and local governance, sustainable urban development and decentralization. Addressing international experts and working with multiple renowned authors from around the globe, the blog is supported and implemented by GIZ's Sector Project "Urbanization, Municipal and Urban Development" on behalf of the German Federal Ministry for Economic Cooperation and Development (BMZ). The articles revolve around governance and finance issues, basic infrastructure and housing, green and smart development and global urban debates.

It is in consideration of these contents that I decided to consider as good starting point for my analysis the articles collected in the site session dedicated to India (available at [this link](https://www.urbanet.info/tag/india/)).



# TWITTER: how do people talk about smart cities?

# Conclusions

# References
